---
downloads: ~/.ansible-downloads/
home: /Users/aurelien

configure_dotfiles: yes
configure_homebrew: yes
configure_osx: yes
configure_iterm: yes
configure_extra_packages: yes
mas_installed_apps: yes
configure_keys: yes

dotfiles_repo: https://github.com/Arinono/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/workspace/misc/dotfiles
dotfiles_files:
  - .zshrc
  - .inputrc
  - .osx
  - .gitconfig
  - .gitignore
  - .zshenv
  - .zlogin
  - .p10k.zsh

homebrew_installed_packages:
  - archey
  - asciinema
  - autoconf
  - automake
  - bash
  - cmake
  - dart
  - deno
  - docker-compose
  - docker-machine
  - dockutil
  - dust
  - ffmpeg
  - git
  - gnupg
  - go
  - hashcat
  - helm
  - htop
  - jq
  - kubernetes-cli
  - lcov
  - libusb
  - mas
  - mysql-client
  - n
  - nmap
  - pinentry
  - postgresql
  - python
  - sqitch
  - sqlite
  - telnet
  - tree
  - wasm-pack
  - watch
  - wget
  - wireguard-go
  - wireguard-tools
  - yarn

homebrew_taps:
  - adoptopenjdk/openjdk
  - dart-lang/dart
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - sqitchers/sqitch

homebrew_cask_appdir: /Applications
homebrew_cask_apps: 
  - 1password
  - brave-browser
  - chromedriver
  - chromium
  - coconutbattery
  - discord
  - docker
  - figma
  - flycut
  - google-chrome
  - google-cloud-sdk
  - insomnia
  - istat-menus
  - iterm2
  - keycastr
  - loom
  - ngrok
  - notion
  - obs
  - signal
  - slack
  - soundsource
  - spotify
  - tweetbot
  - visual-studio-code-insiders
  - vlc

mas_installed_apps:
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 425424353, name: "The Unarchiver" }
mas_email: ""
mas_password: ""

dockitems_to_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - News
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - App Store

dockitems_to_persist:
  - name: System Preferences
    path: /Applications/System Preferences.app
    pos: 1
  - name: 1Password 7
    path: /Applications/1Password 7.app
    pos: 2
  - name: Signal
    path: /Applications/Signal.app
    pos: 3
  - name: Spark
    path: /Applications/Spark.app
    pos: 4
  - name: Brave Browser
    path: /Applications/Brave Browser.app
    pos: 5
  - name: Visual Studio Code - Insiders
    path: /Applications/Visual Studio Code - Insiders.app
    pos: 6
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 7
  - name: Figma
    path: /Applications/Figma.app
    pos: 8
  - name: Slack
    path: /Applications/Slack.app
    pos: 9
  - name: Tandem
    path: /Applications/Tandem.app
    pos: 10
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 11

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
yarn_packages:
  - name: '@vue/cli'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'eslint'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'jest'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'standard-changelog'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'standard-version'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'ts-node'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'ts-watch'
    state: latest
    executable: /usr/local/bin/yarn
  - name: 'typescript'
    state: latest
    executable: /usr/local/bin/yarn
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  - post_provision/install-node.yml

# ITERM
it_default_profile: "{{ lookup('file', 'files/iterm/com.googlecode.iterm2-New_Bookmarks') }}"

main_email: ""

# GPG
gpg_password: ""

# iStatMenu
istat_license: ""

# SoundSource
soundsource_license: ""
