---
- include_tasks: ui.yml
- include_tasks: inputs.yml
- include_tasks: screen.yml
- include_tasks: finder.yml
- include_tasks: dock.yml
- include_tasks: safari.yml
- include_tasks: activity-monitor.yml
- include_tasks: text-edit.yml
- include_tasks: fonts.yml
- include_tasks: my-apps.yml

- name: Run .osx dotfiles.
  shell: "{{ osx_script }}"
  changed_when: false
