###############################################################################
# Safari & WebKit                                                             #
###############################################################################
---
- name: Set Safari’s home page to `about:blank` for faster loading
  osx_defaults:
    domain: com.apple.Safari
    key: HomePage
    type: string
    value: "about:blank"
- name: Prevent Safari from opening ‘safe’ files automatically after downloading
  osx_defaults:
    domain: com.apple.Safari
    key: AutoOpenSafeDownloads
    type: bool
    value: false
- name: Disable Safari’s thumbnail cache for History and Top Sites
  osx_defaults:
    domain: com.apple.Safari
    key: DebugSnapshotsUpdatePolicy
    type: int
    value: 2
- name: Enable Safari’s debug menu
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
- name: Enable the Develop menu and the Web Inspector in Safari
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true
- name: Enable the Develop menu and the Web Inspector in Safari
  osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true
- name: Enable the Develop menu and the Web Inspector in Safari
  osx_defaults:
    domain: com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
    type: bool
    value: true
- name: Add a context menu item for showing the Web Inspector in web views
  osx_defaults:
    domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: bool
    value: true
